"""The CBOM Atlas corpus: ~100 public repositories scanned with ECDAT for the SIH 2026 idea submission.

Each entry: (owner/repo, category, data_class). data_class drives Mosca's X (how long the data must stay
secret): identity/health data lives for decades, session tokens for hours. Categories are chosen to cover
what NCIIPC-regulated operators actually run: India's open digital public infrastructure first.
"""
from __future__ import annotations

CATEGORIES = {
    "india-dpi": "India digital public infrastructure (open source)",
    "identity": "Identity, auth and token libraries",
    "pki": "PKI, certificates and TLS tooling",
    "network": "SSH, VPN and secure transport",
    "crypto-lib": "General-purpose crypto libraries",
    "fintech": "Payments, banking and blockchain",
    "platform": "Messaging, storage and collaboration platforms",
    "pqc": "Post-quantum reference implementations (control group)",
}

REPOS: list[tuple[str, str, str]] = [
    # India digital public infrastructure
    ("mosip/keymanager", "india-dpi", "identity"),
    ("mosip/id-authentication", "india-dpi", "identity"),
    ("mosip/id-repository", "india-dpi", "identity"),
    ("mosip/registration", "india-dpi", "identity"),
    ("mosip/esignet", "india-dpi", "identity"),
    ("mosip/commons", "india-dpi", "identity"),
    ("mosip/pre-registration", "india-dpi", "identity"),
    ("mosip/inji-wallet", "india-dpi", "identity"),
    ("mosip/inji-certify", "india-dpi", "identity"),
    ("mosip/inji-verify", "india-dpi", "identity"),
    ("Sunbird-RC/sunbird-rc-core", "india-dpi", "identity"),
    ("Sunbird-Ed/SunbirdEd-portal", "india-dpi", "pii"),
    ("egovernments/Digit-Core", "india-dpi", "pii"),
    ("beckn/beckn-onix", "india-dpi", "financial"),
    ("beckn/beckn-sandbox", "india-dpi", "financial"),
    ("mosip/admin-services", "india-dpi", "identity"),
    ("mosip/resident-services", "india-dpi", "identity"),
    ("mosip/partner-management-services", "india-dpi", "identity"),
    ("inji/mimoto", "india-dpi", "identity"),
    ("Sunbird-Lern/userorg-service", "india-dpi", "pii"),
    ("Sunbird-Knowlg/knowledge-platform", "india-dpi", "pii"),
    ("OpenG2P/openg2p-registry", "india-dpi", "identity"),
    ("nic-delhi/AarogyaSetu_Android", "india-dpi", "health"),
    ("Bahmni/openmrs-module-bahmniapps", "india-dpi", "health"),
    ("NHA-ABDM/ABDM-wrapper", "india-dpi", "health"),
    ("ONDC-Official/reference-implementations", "india-dpi", "financial"),
    ("Samagra-Development/Doc-Generator", "india-dpi", "pii"),
    ("dhiway/cord", "india-dpi", "identity"),
    # identity / auth / tokens
    ("jpadilla/pyjwt", "identity", "session"),
    ("auth0/node-jsonwebtoken", "identity", "session"),
    ("golang-jwt/jwt", "identity", "session"),
    ("panva/jose", "identity", "session"),
    ("lepture/authlib", "identity", "session"),
    ("oauthlib/oauthlib", "identity", "session"),
    ("jwtk/jjwt", "identity", "session"),
    ("auth0/java-jwt", "identity", "session"),
    ("jaredhanson/passport", "identity", "session"),
    ("ory/hydra", "identity", "session"),
    ("ory/kratos", "identity", "pii"),
    ("dexidp/dex", "identity", "session"),
    ("casdoor/casdoor", "identity", "pii"),
    ("supertokens/supertokens-core", "identity", "session"),
    ("mpdavis/python-jose", "identity", "session"),
    ("IdentityPython/pysaml2", "identity", "session"),
    ("SAML-Toolkits/python3-saml", "identity", "session"),
    ("pac4j/pac4j", "identity", "session"),
    # PKI / certificates / TLS tooling
    ("certbot/certbot", "pki", "default"),
    ("acmesh-official/acme.sh", "pki", "default"),
    ("smallstep/certificates", "pki", "default"),
    ("smallstep/cli", "pki", "default"),
    ("cloudflare/cfssl", "pki", "default"),
    ("FiloSottile/mkcert", "pki", "default"),
    ("go-acme/lego", "pki", "default"),
    ("caddyserver/caddy", "pki", "default"),
    ("letsencrypt/boulder", "pki", "default"),
    ("OpenVPN/easy-rsa", "pki", "default"),
    ("hashicorp/go-rootcerts", "pki", "default"),
    ("nabla-c0d3/sslyze", "pki", "default"),
    # network / SSH / VPN
    ("paramiko/paramiko", "network", "pii"),
    ("openssh/openssh-portable", "network", "pii"),
    ("mscdex/ssh2", "network", "pii"),
    ("WireGuard/wireguard-go", "network", "pii"),
    ("OpenVPN/openvpn", "network", "pii"),
    ("libssh2/libssh2", "network", "pii"),
    ("ronf/asyncssh", "network", "pii"),
    ("golang/crypto", "network", "pii"),
    ("gravitational/teleport", "network", "pii"),
    ("fatedier/frp", "network", "pii"),
    ("jedisct1/dnscrypt-proxy", "network", "pii"),
    ("quic-go/quic-go", "network", "pii"),
    # general crypto libraries
    ("pyca/cryptography", "crypto-lib", "default"),
    ("Legrandin/pycryptodome", "crypto-lib", "default"),
    ("jedisct1/libsodium", "crypto-lib", "default"),
    ("Mbed-TLS/mbedtls", "crypto-lib", "default"),
    ("wolfSSL/wolfssl", "crypto-lib", "default"),
    ("brix/crypto-js", "crypto-lib", "default"),
    ("digitalbazaar/forge", "crypto-lib", "default"),
    ("paulmillr/noble-curves", "crypto-lib", "default"),
    ("indutny/elliptic", "crypto-lib", "default"),
    ("tink-crypto/tink-java", "crypto-lib", "default"),
    ("tink-crypto/tink-py", "crypto-lib", "default"),
    ("pyca/bcrypt", "crypto-lib", "default"),
    ("pyca/pynacl", "crypto-lib", "default"),
    ("kokke/tiny-AES-c", "crypto-lib", "default"),
    # fintech / payments / blockchain
    ("ethereum/web3.py", "fintech", "financial"),
    ("ethers-io/ethers.js", "fintech", "financial"),
    ("bitcoinjs/bitcoinjs-lib", "fintech", "financial"),
    ("hyperledger/fabric", "fintech", "financial"),
    ("hyperledger/fabric-sdk-node", "fintech", "financial"),
    ("openMF/web-app", "fintech", "financial"),
    ("juspay/hyperswitch", "fintech", "financial"),
    ("stripe/stripe-python", "fintech", "financial"),
    ("razorpay/razorpay-python", "fintech", "financial"),
    ("moov-io/ach", "fintech", "financial"),
    ("jpos/jPOS", "fintech", "financial"),
    ("bitcoin/bips", "fintech", "financial"),
    # platforms
    ("matrix-org/synapse", "platform", "pii"),
    ("signalapp/libsignal", "platform", "pii"),
    ("bitwarden/clients", "platform", "defence"),
    ("keepassxreboot/keepassxc", "platform", "defence"),
    ("minio/minio", "platform", "pii"),
    ("hashicorp/vault", "platform", "defence"),
    ("go-gitea/gitea", "platform", "pii"),
    ("mattermost/mattermost-plugin-starter-template", "platform", "pii"),
    ("zulip/zulip", "platform", "pii"),
    ("home-assistant/core", "platform", "pii"),
    # post-quantum control group: should come out SAFE-heavy
    ("open-quantum-safe/liboqs-python", "pqc", "default"),
    ("open-quantum-safe/oqs-provider", "pqc", "default"),
    ("cloudflare/circl", "pqc", "default"),
    ("pq-crystals/kyber", "pqc", "default"),
    ("pq-crystals/dilithium", "pqc", "default"),
    ("GiacomoPope/kyber-py", "pqc", "default"),
    ("GiacomoPope/dilithium-py", "pqc", "default"),
    ("PQClean/PQClean", "pqc", "default"),
    ("open-quantum-safe/liboqs", "pqc", "default"),
    ("pq-code-package/mlkem-native", "pqc", "default"),
]
